# Generated by Django 4.0.1 on 2022-01-29 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo_sucursal', verbose_name='logo')),
                ('descripcion', models.TextField(help_text='Ingrese una descripcion de la sucursal')),
                ('direccion', models.TextField(help_text='Ingrese la direccion de la tienda')),
                ('telefono', models.TextField(help_text='Ingrese el telefono de la ubicacion')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.sucursal'),
        ),
    ]
