# Generated by Django 4.0.1 on 2022-01-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_sucursal_user_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='descripcion',
            field=models.CharField(help_text='Ingrese una descripcion de la sucursal', max_length=50),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='telefono',
            field=models.CharField(help_text='Ingrese el telefono de la ubicacion', max_length=50),
        ),
    ]
