# Generated by Django 4.0.1 on 2022-01-29 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_sucursal_descripcion_alter_sucursal_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(help_text='Ingrese la categoria del producto', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.CharField(help_text='Ingrese la presentacion', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(help_text='Ingrese el nombre del producto', max_length=100)),
                ('descripcion', models.CharField(help_text='Ingrese la descripcion del producto', max_length=100)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.categoria')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(help_text='Ingrese la cantidad de producto')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Ingrese la cantidad', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('presentacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.presentacion')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.producto')),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='StockGloval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(help_text='Ingrese la cantidad del producto global')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Ingrese el precio del producto', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('presentacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.presentacion')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.producto')),
            ],
        ),
    ]
