# Generated by Django 4.0.1 on 2022-01-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_categoria_presentacion_producto_stocksucursal_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockGloval',
            new_name='ProductoStockGloval',
        ),
        migrations.RenameModel(
            old_name='StockSucursal',
            new_name='ProductoStockSucursal',
        ),
    ]
