# Generated by Django 4.0.1 on 2022-01-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_rename_stockgloval_productostockgloval_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductoStockGloval',
            new_name='ProductoStockGlobal',
        ),
    ]
