# Generated by Django 4.0.1 on 2022-01-30 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_rename_productostockgloval_productostockglobal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(help_text='Ingrese la cantidad a comprar')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Ingrese el precio del producto', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto_stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.productostocksucursal')),
            ],
        ),
    ]
