# Generated by Django 4.0.1 on 2022-01-30 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_ventas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now=True, help_text='Ingrese la fecha de la venta')),
                ('numero_factura', models.CharField(help_text='Ingrese el numero de factura', max_length=50)),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.sucursal')),
            ],
        ),
        migrations.AddField(
            model_name='ventas',
            name='factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.factura'),
        ),
    ]
