# Generated by Django 4.0.1 on 2022-01-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_factura_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='total_con_iva',
            field=models.DecimalField(decimal_places=2, help_text='Total de la suma de todos los productos mas el total del iva', max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='total_por_iva',
            field=models.DecimalField(decimal_places=2, help_text='Total resultante de multiplicar el total por el procentaje de iva', max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='total_sin_iva',
            field=models.DecimalField(decimal_places=2, help_text='Total de la suma de todos los productos sin iva', max_digits=100, null=True),
        ),
    ]
