# Generated by Django 4.0.1 on 2022-01-30 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_rename_factura_facturaventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='productostocksucursal',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
