# Generated by Django 4.0.1 on 2022-02-06 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_productostocksucursal_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productostocksucursal',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='productostocksucursal',
            name='usuario',
        ),
        migrations.CreateModel(
            name='InventarioProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripcion de la carga de inventario', max_length=100)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, help_text='fecha de creacion')),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.sucursal')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='productostocksucursal',
            name='inventario_productos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.inventarioproductos'),
        ),
    ]
