# Generated by Django 4.0.1 on 2022-02-06 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0017_inventarioproductos_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productostocksucursal',
            name='usuario',
        ),
        migrations.AddField(
            model_name='inventarioproductos',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
