# Generated by Django 4.0.1 on 2022-02-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0018_remove_productostocksucursal_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productostocksucursal',
            name='costo',
            field=models.DecimalField(decimal_places=2, help_text='Ingrese el costo de compra del producto ', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productostocksucursal',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='Ingrese el precio de venta del producto', max_digits=10, null=True),
        ),
    ]
