# Generated by Django 4.0.1 on 2022-02-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0019_productostocksucursal_costo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_barra',
            field=models.CharField(help_text='Ingrese el codigo de barra del producto', max_length=100, null=True),
        ),
    ]
