# Generated by Django 4.0.1 on 2022-02-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0020_producto_codigo_barra'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Ingrese la fecha de vencimiento', null=True),
        ),
    ]
