# Generated by Django 4.0.1 on 2022-02-13 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0021_producto_fecha_vencimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(help_text='Ingrese la cantidad a comprar')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Ingrese el precio del producto', max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now=True, help_text='Ingrese la fecha de la venta')),
                ('numero_factura', models.CharField(help_text='Ingrese el numero de factura', max_length=50, null=True)),
                ('total_por_iva', models.DecimalField(decimal_places=2, help_text='Total resultante de multiplicar el total por el procentaje de iva', max_digits=100, null=True)),
                ('total_sin_iva', models.DecimalField(decimal_places=2, help_text='Total de la suma de todos los productos sin iva', max_digits=100, null=True)),
                ('total_con_iva', models.DecimalField(decimal_places=2, help_text='Total de la suma de todos los productos mas el total del iva', max_digits=100, null=True)),
                ('sucursal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.sucursal')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='producto_stock',
        ),
        migrations.DeleteModel(
            name='FacturaVentas',
        ),
        migrations.DeleteModel(
            name='Ventas',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='producto_stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.productostocksucursal'),
        ),
    ]
