# Generated by Django 4.0.1 on 2022-02-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0022_detalleventa_venta_remove_ventas_factura_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='total_por_iva',
            new_name='total_iva',
        ),
    ]
