# Generated by Django 4.0.1 on 2022-02-13 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0023_rename_total_por_iva_venta_total_iva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del proveedor', max_length=100, null=True)),
                ('empresa', models.CharField(help_text='Ingrese el nombre de la empresa', max_length=100, null=True)),
                ('direccion', models.TextField(help_text='Ingrese la direccion del proveedor', null=True)),
                ('celular', models.CharField(help_text='Ingrese el Celular del proveedor', max_length=11, null=True)),
                ('telefono', models.CharField(help_text='Ingrese el telefono del proveedor', max_length=11, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(help_text='Seleccione el proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.proveedor'),
        ),
    ]
