# Generated by Django 4.0.1 on 2022-02-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0024_proveedor_producto_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productostocksucursal',
            name='costo',
            field=models.FloatField(help_text='Ingrese el costo de compra del producto ', null=True),
        ),
        migrations.AlterField(
            model_name='productostocksucursal',
            name='precio',
            field=models.FloatField(help_text='Ingrese el precio de venta del producto', null=True),
        ),
        migrations.AlterField(
            model_name='productostocksucursal',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
