# Generated by Django 4.0.1 on 2022-02-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0025_alter_productostocksucursal_costo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioproductos',
            name='total',
            field=models.FloatField(help_text='Ingrese el total de el inventario', null=True),
        ),
    ]
