# Generated by Django 4.0.1 on 2022-02-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0028_cargaproductos_detallecargaproductos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargaproductos',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
