# Generated by Django 4.0.1 on 2022-02-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0031_detallecargaproductos_cantidad_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecargaproductos',
            name='nueva_cantidad',
            field=models.IntegerField(help_text='Ingrese la nueva cantidad', null=True),
        ),
        migrations.AlterField(
            model_name='detallecargaproductos',
            name='cantidad_anterior',
            field=models.IntegerField(help_text='Ingrese la cantidad anterior del producto', null=True),
        ),
    ]
