# Generated by Django 4.0.1 on 2022-02-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0033_remove_productostocksucursal_inventario_productos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productostocksucursal',
            name='total',
        ),
    ]
