# Generated by Django 4.0.1 on 2022-02-20 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0035_productostocksucursal_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescargaProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_descarga', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(help_text='Ingrese la descripcion del evento de descarga', max_length=100)),
                ('total', models.FloatField(null=True)),
                ('sucursal', models.ForeignKey(help_text='Sucursal de donde se hace la descarga', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.sucursal')),
                ('usuario', models.ForeignKey(null='Usuario que hace ka descarga', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleDescargaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_anterior', models.IntegerField(help_text='Ingrese la cantidad anterior del producto', null=True)),
                ('cantidad', models.IntegerField(help_text='Ingrese la cantidad del producto', null=True)),
                ('nueva_cantidad', models.IntegerField(help_text='Ingrese la nueva cantidad', null=True)),
                ('costo_anterior', models.FloatField(help_text='Ingrese el costo anterior', null=True)),
                ('costo', models.FloatField(help_text='Ingrese el costo del producto', null=True)),
                ('precio_anterior', models.FloatField(help_text='Ingrese el precio anterior', null=True)),
                ('precio', models.FloatField(help_text='Ingrese el precio a como se va dar el producto en la venta', null=True)),
                ('total', models.FloatField(null=True)),
                ('descarga_productos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.descargaproductos')),
                ('presentacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.presentacion')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.producto')),
            ],
        ),
    ]
