# Generated by Django 4.0.1 on 2022-02-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0036_descargaproductos_detalledescargaproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_producto',
            field=models.CharField(help_text='Codigo del producto', max_length=500, null=True),
        ),
    ]
