# Generated by Django 4.0.1 on 2022-02-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0038_remove_detalledescargaproducto_costo_anterior_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalledescargaproducto',
            old_name='cantidad',
            new_name='cantidad_descargada',
        ),
    ]
