# Generated by Django 4.0.2 on 2022-03-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0039_rename_cantidad_detalledescargaproducto_cantidad_descargada'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(help_text='Ingrese el tipo de Usuario', max_length=50)),
            ],
        ),
    ]
