# Generated by Django 4.0.2 on 2022-03-15 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0040_tipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo_usuario',
            field=models.ForeignKey(help_text='Ingrese el tipo de Usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.tipousuario'),
        ),
    ]
