# Generated by Django 4.0.1 on 2022-03-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0041_user_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total_con_iva',
            field=models.FloatField(help_text='Total de la suma de todos los productos mas el total del iva', max_length=65, null=True),
        ),
    ]
