# Generated by Django 4.0.1 on 2022-07-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0045_devolucionventa_detalledevolucionventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucionventa',
            name='total_devolucion',
            field=models.FloatField(help_text='Ingrese el total de la devolucion', null=True),
        ),
        migrations.AlterField(
            model_name='detalledevolucionventa',
            name='cantidad_devolver',
            field=models.IntegerField(help_text='Ingrese la cantidad a devolver', null=True),
        ),
    ]
