# Generated by Django 4.0.1 on 2022-07-05 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0046_devolucionventa_total_devolucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucionventa',
            name='sucursal',
            field=models.ForeignKey(help_text='Ingrese la sucursal en donde se realiza la devolucion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.sucursal'),
        ),
    ]
