# Generated by Django 4.0.1 on 2022-07-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0048_devolucionventa_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalledevolucionventa',
            name='usuario',
        ),
    ]
