# Generated by Django 4.0.1 on 2022-07-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0049_remove_detalledevolucionventa_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucionventa',
            name='fecha_devolucion',
            field=models.DateField(auto_now=True, help_text='Ingrese la fecha de devolucion', null=True),
        ),
    ]
