# Generated by Django 4.0.1 on 2022-07-06 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0050_alter_devolucionventa_fecha_devolucion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalledevolucionventa',
            name='producto',
        ),
        migrations.AddField(
            model_name='detalledevolucionventa',
            name='producto_stock_suc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.productostocksucursal'),
        ),
    ]
