# Generated by Django 4.0.1 on 2022-08-08 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0051_remove_detalledevolucionventa_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVentaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_servicio', models.TextField(help_text='ingrese la descripcion del servicio', null=True)),
                ('precio', models.FloatField(help_text='Ingrese el precio del servicio')),
                ('factura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.venta')),
            ],
        ),
    ]
