# Generated by Django 4.0.1 on 2022-11-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0052_detalleventaservicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correlativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(help_text='Ingrese el nombre del documento', max_length=100)),
                ('numero_correlativo_actual', models.IntegerField(help_text='Ingrese el numero de correlativo actual')),
            ],
        ),
    ]
