# Generated by Django 4.0.1 on 2022-11-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0053_correlativos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correlativos',
            name='numero_correlativo_actual',
            field=models.CharField(help_text='Ingrese el numero de correlativo actual', max_length=100),
        ),
    ]
