# Generated by Django 4.0.1 on 2022-11-08 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0054_alter_correlativos_numero_correlativo_actual'),
    ]

    operations = [
        migrations.CreateModel(
            name='AperturaCorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_apertura', models.DateTimeField(auto_now=True, help_text='fecha y hora de apertura se generara automaticamente porque se registra el mismo momento que se habre apertura')),
                ('monto_de_apertura', models.FloatField(help_text='Ingrese el monto de apertura de su turno')),
                ('monto_de_corte', models.FloatField(help_text='Ingrese el monto de corte de su turno')),
                ('fecha_de_corte', models.DateTimeField(help_text='Ingrese la fecha que se realizara el corte')),
                ('estado_de_apertura', models.BooleanField(help_text='Estado de la apertura, servira para saber si hay una apertura activa para empezar a vender')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
