# Generated by Django 4.0.1 on 2022-11-08 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0055_aperturacorte'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='apertura_corte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.aperturacorte'),
        ),
    ]
