# Generated by Django 4.0.1 on 2022-11-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0056_detalleventa_apertura_corte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperturacorte',
            name='fecha_de_corte',
            field=models.DateTimeField(blank=True, help_text='Ingrese la fecha que se realizara el corte', null=True),
        ),
        migrations.AlterField(
            model_name='aperturacorte',
            name='monto_de_corte',
            field=models.FloatField(blank=True, help_text='Ingrese el monto de corte de su turno', null=True),
        ),
    ]
