# Generated by Django 4.0.1 on 2022-11-09 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0057_alter_aperturacorte_fecha_de_corte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_caja', models.CharField(help_text='Ingrese el numero', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='caja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.caja'),
        ),
    ]
