# Generated by Django 4.0.1 on 2022-11-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0058_caja_user_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturacorte',
            name='ultima_apertura',
            field=models.BooleanField(blank=True, help_text='Este estado servira para saber si es la ultima apertura', null=True),
        ),
    ]
