# Generated by Django 4.0.1 on 2022-11-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0059_aperturacorte_ultima_apertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperturacorte',
            name='ultima_apertura',
            field=models.BooleanField(help_text='Este estado servira para saber si es la ultima apertura', null=True),
        ),
    ]
