# Generated by Django 4.0.1 on 2022-11-10 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0060_alter_aperturacorte_ultima_apertura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='apertura_corte',
        ),
        migrations.AddField(
            model_name='venta',
            name='apertura_corte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.aperturacorte'),
        ),
    ]
