# Generated by Django 4.0.1 on 2022-11-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0061_remove_detalleventa_apertura_corte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturacorte',
            name='diferencia',
            field=models.FloatField(blank=True, help_text='Sirve para agregar alguna diferencia que haya en este el corte', null=True),
        ),
        migrations.AddField(
            model_name='aperturacorte',
            name='observacion',
            field=models.TextField(blank=True, help_text='Servira para agregarle una observaciones en las aperturas', null=True),
        ),
    ]
