# Generated by Django 4.0.1 on 2022-11-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0062_aperturacorte_diferencia_aperturacorte_observacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aperturacorte',
            old_name='diferencia',
            new_name='diferencia_de_corte',
        ),
        migrations.AddField(
            model_name='aperturacorte',
            name='diferencia_de_apertura',
            field=models.FloatField(blank=True, help_text='servira para registrar la diferencia de apertura por si hay meno o mas dinero', null=True),
        ),
    ]
