# Generated by Django 4.0.1 on 2022-11-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0063_rename_diferencia_aperturacorte_diferencia_de_corte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturacorte',
            name='corte_global',
            field=models.BooleanField(blank=True, help_text='Servira para establecer que es el ultimo corte del dia y no se tomara en cuenta a la hora de realizar nueva apertura se asumira que la apertura anterior es cero', null=True),
        ),
    ]
