# Generated by Django 4.0.1 on 2022-11-11 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0064_aperturacorte_corte_global'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aperturacorte',
            old_name='usuario',
            new_name='usuario_corte',
        ),
    ]
