# Generated by Django 4.0.1 on 2022-11-11 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0065_rename_usuario_aperturacorte_usuario_corte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aperturacorte',
            old_name='usuario_corte',
            new_name='usuario_apertura',
        ),
    ]
