# Generated by Django 4.0.1 on 2022-11-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0066_rename_usuario_corte_aperturacorte_usuario_apertura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aperturacorte',
            old_name='usuario_apertura',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='aperturacorte',
            name='nombre_usuario_corte',
            field=models.CharField(blank=True, help_text='servira para poner el nombre de usuario que realizara el corte', max_length=100, null=True),
        ),
    ]
