# Generated by Django 4.0.1 on 2022-11-11 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0067_rename_usuario_apertura_aperturacorte_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aperturacorte',
            old_name='nombre_usuario_corte',
            new_name='usuario_de_cierre',
        ),
    ]
