# Generated by Django 4.0.1 on 2022-11-11 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0068_rename_nombre_usuario_corte_aperturacorte_usuario_de_cierre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aperturacorte',
            old_name='usuario_de_cierre',
            new_name='nombre_usuario_corte',
        ),
    ]
