# Generated by Django 4.0.1 on 2022-11-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0069_rename_usuario_de_cierre_aperturacorte_nombre_usuario_corte'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturacorte',
            name='nombre_usuario_cierre',
            field=models.CharField(blank=True, help_text='Servira para saber que usuario cerro', max_length=100, null=True),
        ),
    ]
