# Generated by Django 4.0.1 on 2022-11-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0070_aperturacorte_nombre_usuario_cierre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barra',
            field=models.CharField(blank=True, help_text='Ingrese el codigo de barra del producto', max_length=100, null=True),
        ),
    ]
