# Generated by Django 4.0.1 on 2022-11-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0071_alter_producto_codigo_barra'),
    ]

    operations = [
        migrations.AddField(
            model_name='productostocksucursal',
            name='fecha_de_registro',
            field=models.DateTimeField(auto_now_add=True, help_text='Servira para saber que dia se registro', null=True),
        ),
    ]
