# Generated by Django 4.0.1 on 2022-11-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0072_productostocksucursal_fecha_de_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_de_registro',
            field=models.DateTimeField(auto_now_add=True, help_text='Ingrese la fecha de registro', null=True),
        ),
    ]
