# Generated by Django 4.0.1 on 2022-11-20 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0073_producto_fecha_de_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperturacorte',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.sucursal'),
        ),
    ]
