# Generated by Django 4.0.1 on 2022-11-22 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0074_aperturacorte_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='correlativos',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.sucursal'),
        ),
    ]
