# Generated by Django 4.0.1 on 2022-11-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0075_correlativos_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEntradaSalidaEfectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entrada_salida', models.CharField(help_text='Ingrese el tipo de entrada y salida', max_length=100)),
            ],
        ),
    ]
