# Generated by Django 4.0.1 on 2022-11-22 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0076_tipoentradasalidaefectivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaSalidaEfectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(help_text='Ingrese la descripcion de la entrada o salida de efectivo de caja')),
                ('monto', models.FloatField(help_text='Ingrese el monto de la salida o entrada de efectivo')),
                ('tipo_entrada_salida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.tipoentradasalidaefectivo')),
            ],
        ),
    ]
