# Generated by Django 4.0.1 on 2022-11-22 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0077_entradasalidaefectivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradasalidaefectivo',
            name='caja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.caja'),
        ),
    ]
