# Generated by Django 4.0.1 on 2022-11-22 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0078_entradasalidaefectivo_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradasalidaefectivo',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
