# Generated by Django 4.0.1 on 2022-11-29 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0079_entradasalidaefectivo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productostocksucursal',
            name='cantidad',
            field=models.IntegerField(blank=True, help_text='Ingrese la cantidad de producto'),
        ),
        migrations.AlterField(
            model_name='productostocksucursal',
            name='costo',
            field=models.FloatField(blank=True, help_text='Ingrese el costo de compra del producto ', null=True),
        ),
        migrations.AlterField(
            model_name='productostocksucursal',
            name='precio',
            field=models.FloatField(blank=True, help_text='Ingrese el precio de venta del producto', null=True),
        ),
        migrations.AlterField(
            model_name='productostocksucursal',
            name='presentacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.presentacion'),
        ),
        migrations.AlterField(
            model_name='productostocksucursal',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.producto'),
        ),
        migrations.AlterField(
            model_name='productostocksucursal',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.sucursal'),
        ),
        migrations.AlterField(
            model_name='productostocksucursal',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
