# Generated by Django 4.0.1 on 2022-11-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0080_alter_productostocksucursal_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productostocksucursal',
            name='cantidad',
            field=models.IntegerField(blank=True, help_text='Ingrese la cantidad de producto', null=True),
        ),
    ]
