# Generated by Django 4.0.1 on 2023-04-10 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0082_alter_productostocksucursal_cantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denominaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(help_text='nombre de la denominacion', max_length=50)),
                ('precio', models.FloatField(help_text='ingrese el precio de la denominacion', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDenominacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_denominacion', models.CharField(help_text='nombre de la denominacion', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transaccion', models.CharField(help_text='tipo de transaccion', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(help_text='Nombre del cliente', max_length=50)),
                ('apellido_cliente', models.CharField(help_text='Apellido del cliente', max_length=50)),
                ('fecha_transaccion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la transaccion')),
                ('total', models.FloatField(help_text='total de la transaccion', null=True)),
                ('tipo_transacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.tipotransaccion')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(help_text='cantidad de esta denominacion', null=True)),
                ('total', models.FloatField(help_text='Ingrese el total por denominacion', null=True)),
                ('denominacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.denominaciones')),
                ('transaccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.transaccion')),
            ],
        ),
        migrations.AddField(
            model_name='denominaciones',
            name='tipo_denominacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.tipotransaccion'),
        ),
    ]
