# Generated by Django 4.0.1 on 2023-04-11 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0083_denominaciones_tipodenominacion_tipotransaccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.sucursal'),
        ),
    ]
