# Generated by Django 4.0.1 on 2023-04-11 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0084_transaccion_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denominaciones',
            name='tipo_denominacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.tipodenominacion'),
        ),
    ]
