# Generated by Django 4.0.1 on 2023-04-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0085_alter_denominaciones_tipo_denominacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='concepto',
            field=models.TextField(help_text='concepto sobre que trata la transaccion', null=True),
        ),
    ]
