# Generated by Django 4.0.1 on 2023-04-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0086_transaccion_concepto'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='total_billete',
            field=models.FloatField(help_text='el total en billete', null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='total_moneda',
            field=models.FloatField(help_text='El total moneda', null=True),
        ),
    ]
