# Generated by Django 4.0.1 on 2023-04-24 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0087_transaccion_total_billete_transaccion_total_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='correlativo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.correlativos'),
        ),
    ]
