# Generated by Django 4.0.1 on 2023-04-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0088_transaccion_correlativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='correlativo',
            field=models.CharField(help_text='numero de transaccion', max_length=50, null=True),
        ),
    ]
