# Generated by Django 4.0.1 on 2023-04-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0089_alter_transaccion_correlativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipotransaccion',
            name='tipo_transaccion',
        ),
        migrations.AddField(
            model_name='tipotransaccion',
            name='nombre_tipo_transaccion',
            field=models.CharField(help_text='tipo de transaccion', max_length=50, null=True),
        ),
    ]
