# Generated by Django 4.0.1 on 2023-04-24 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0090_remove_tipotransaccion_tipo_transaccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='tipo_transacion',
            new_name='tipo_transaccion',
        ),
    ]
